# -*- coding: utf-8 -*-
"""NLP7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KECGJrcfUUr1oxHj19t5JnIl-g4z1G_l
"""

!pip install nltk

import nltk
from nltk.chat.util import Chat, reflections

college_pairs = [
    [r"(hi|hello|hey)", ["Hello! I'm the college enquiry chatbot. How can I help you today?"]],
    [r"(.*)college(.*)", ["Our college offers a variety of undergraduate and postgraduate programs. What specific information are you looking for?"]],
    [r"admission", ["The admission process typically involves submitting an online application, providing academic transcripts, and possibly attending an interview. Do you have specific questions about the admission process?"]],
    [r"courses", ["We offer a range of courses including Computer Science, Business Administration, and Biology. Which department or program are you interested in?"]],
    [r"curricular", ["Our curricular activities include a mix of lectures, workshops, and practical sessions to provide a holistic learning experience. Is there anything specific you would like to know about our curricular activities?"]],
    [r"academic calendar", ["The academic calendar typically includes important dates such as the start and end of the semester, holidays, and examination periods. Do you have a specific question about the academic calendar?"]],
    [r"syllabus", ["The syllabus for each program is designed to cover a wide range of topics. Could you specify the program or department you are interested in?"]],
    [r"events", ["We organize various events throughout the year, including cultural festivals, seminars, and sports events. Is there a particular type of event you are interested in?"]],
    [r"students chapter", ["Our students' chapter provides a platform for students to engage in extracurricular activities, networking, and skill development. Would you like more details about a specific students' chapter?"]],
    [r"student portal", ["The student portal is an online platform where students can access academic information, grades, and other relevant details. For login credentials or technical issues, please contact the IT department."]],
    [r"contact", ["You can contact the college administration at admin@examplecollege.com or call us at +1-123-456-7890. How else can I assist you?"]],
    [r"quit", ["Thank you for inquiring about our college. If you have more questions, feel free to ask. Have a great day!"]],
]

college_chatbot = Chat(college_pairs, reflections)

def college_enquiry_chat():
    print("Hello! I'm the college enquiry chatbot. How can I help you today?")
    while True:
        user_input = input("You: ")
        if user_input.lower() == 'quit':
            print("College Chatbot: Thank you for inquiring about our college. Have a great day!")
            break
        response = college_chatbot.respond(user_input)
        print("College Chatbot:", response)

college_enquiry_chat()